service: thermostat-iot

plugins:
  - serverless-azure-functions
  - serverless-webpack
  - serverless-offline

provider:
  name: azure
  stage: dev
  region: westeurope
  resourceGroup: iot
  runtime: nodejs10.x
  environment:
    VARIABLE_FOO: 'foo'

functions:
  changeHeaterStatus:
    handler: src/changeHeaterStatus/index.httpTrigger
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: /heaterStatus
          authLevel: function
  registerTemperatureSensor:
    handler: src/registerTemperatureSensor/index.httpTrigger
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: /temperatureSensor
          authLevel: function
  getSensorConnectionString:
    handler: src/getSensorConnectionString/index.httpTrigger
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: /sensorConnectionString/{deviceId}
          authLevel: function

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true