export enum DeviceMessageType {
  GET_HEATER_STATUS = 'GET_HEATER_STATUS',
  SET_INITIAL_HEATER_STATUS = 'SET_INITIAL_HEATER_STATUS',
  CHANGE_HEATER_STATUS = 'CHANGE_HEATER_STATUS',
  HEATER_STATUS_CHANGED = 'HEADER_STATUS_CHANGED'
}
